:lang: en
:toc:

[[cha:getting-linuxcnc]]
= Getting LinuxCNC(((Getting LinuxCNC)))

== Overview

This document describes the recommended way to download
and make a fresh install of LinuxCNC.  There are also
<<sec:_alternate_install_methods,Alternate Install Methods>> for the
adventurous.  If you have an existing install that you want to upgrade,
go to the <<cha:updating-linuxcnc,Updating LinuxCNC>> section instead.

NOTE: LinuxCNC requires a special kernel with real-time extensions.
There are three possibilities here: preempt-rt, RTAI or Xenomai. In
addition there are two versions of LinuxCNC which work with these kernels.
See the table below for details.

Fresh installs of LinuxCNC are most easily created using the Live/Install
Image.  This is a hybrid ISO filesystem image that can be written to a
USB storage device or a DVD and used to boot a computer.  At boot time
you will be given a choice of booting the "Live" system (to run LinuxCNC
without making any permanent changes to your computer) or booting the
Installer (to install LinuxCNC and its operating system onto your
computer's hard drive).

The outline of the process looks like this:

. Download the Live/Install Image.
. Write the image to a USB storage device or DVD.
. Boot the Live system to test out LinuxCNC.
. Boot the Installer to install LinuxCNC.

== Download the image

This section describes some methods for downloading the Live/Install
Image.

[[sec:_normal_download]]
=== Normal Download

For x86 PCs Download the Live/Install CD by clicking here:

https://linuxcnc.org/iso/linuxcnc-2.8.4-buster.iso

For the Raspberry Pi a complete SD card image is available here:

https://linuxcnc.org/iso/linuxcnc-2.8.1-pi4.zip (this will auto-update
to 2.8.4)

This can be installed using the normal Pi
https://www.raspberrypi.org/documentation/installation/installing-images/README.md[install process]
including with the Raspberry Pi Imager app.

This SD image is reported not to work with the Raspberry Pi4 8GB model.
Note also that this version of the SD image limits available memory to
3GB as this is necessary to persuade it to run with both WiFi and USB
working  on some versions of the Pi. You can experiment with removing
this limit by editing the config-rt.txt file in the boot directory. If
you can't boot after the change then the file can be edited back by
mounting the SD card in a a different computer (maybe even a Pi with a
USB card reader).

=== Download using zsync

zsync is a download application that efficiently resumes interrupted
downloads and efficiently transfers large files with small modifications
(if you have an older local copy).  Use zsync if you have trouble
downloading the image using the <<sec:_normal_download,Normal Download>>
method.

.zsync in Linux

* Install zsync using Synaptic or, by running the following in a
  <<faq:terminal,terminal>>
+
----
sudo apt-get install zsync
----

* Then run this command to download the iso to your computer
+
----
zsync https://linuxcnc.org/iso/linuxcnc-2.8.4-buster.iso
----
+
or
+
----
zsync https://linuxcnc.org/iso/linuxcnc-2.8.1-pi4.zip.zsync
----

.zsync in Windows

There is a Windows port of zsync. It works as a console application. It
can be downloaded from:

https://www.assembla.com/spaces/zsync-windows/documents

=== Verify the image

(This step is unnecessary if you used zsync)

. After downloading, verify the checksum of the image to ensure integrity.
+
----
md5sum linuxcnc-2.8.4-buster.iso
----
+
or
+
----
sha256sum linuxcnc-2.8.4-buster.iso
----

. Then compare to these checksums
+
-----
md5sum: 8a6e6abd2c792c3e06fbee0ed049ed41
sha256sum: 0bfeac3ddfe1bdbf5ca4dad84eeec165741d3f253a16b75e4405c06b7b489700
-----

.Verify md5sum on Windows or Mac
Windows and Mac OS X do not come with an md5sum program, but there are
alternatives.  More information can be found at:
https://help.ubuntu.com/community/HowToMD5SUM[How To MD5SUM]

== Write the image to a bootable device

The Raspberry Pi image is a completes SD card image and should be
written to an SD card in
https://www.raspberrypi.org/documentation/installation/installing-images/README.md[the normal way].

The LinuxCNC Live/Install ISO Image is a hybrid ISO image which can
be written directly to a USB storage device (flash drive) or a DVD and
used to boot a computer. The image is too large to fit on a CD.

.Writing the image to a USB storage device in Linux
. Connect a USB storage device (for example a flash drive or thumb
  drive type device).
. Determine the device file corresponding to the USB flash drive.
  This information can be found in the output of `dmesg` after
  connecting the device.  `/proc/partitions` may also be helpful.
. Use the `dd` command to write the image to your USB storage device.
  For example, if your storage device showed up as `/dev/sde`,
  then use this command:
+
-----
dd if=linuxcnc-2.8.4-buster.iso of=/dev/sde
-----

.Writing the image to a USB storage device in Mac OSX
. Open a terminal and type
+
-----
diskutil list
-----

. Insert the USB and note the name of the new disk that appears, eg
  /dev/disk5
. unmount the USB. The number found above should be substituted in place
  of the N
+
-----
diskutil unmountDisk /dev/diskN
-----

. Transfer the data with dd, as for Linux above. Note that the disk name
  has an added "r" at the beginning
+
-----
sudo dd if=/path-to.iso of=/dev/rdiskN bs=1m
-----

. Note that this may take a long time to complete and there will be no
  feedback during the process.

.Writing the image to a DVD in Linux
. Insert a blank DVD into your burner. A 'CD/DVD Creator' or 'Choose
  Disc Type' window will pop up. Close this, as we will not be using it.
. Browse to the downloaded image in the file browser.
. Right click on the ISO image file and choose Write to Disc.
. Select the write speed. It is recommended that you write at the lowest
  possible speed.
. Start the burning process.
. If a 'choose a file name for the disc image' window pops up, just pick
  OK.

.Writing the image to a DVD in Windows
. Download and install Infra Recorder, a free and open source image
  burning program: http://infrarecorder.org/
. Insert a blank CD in the drive and select Do nothing or Cancel if an
  auto-run dialog pops up.
. Open Infra Recorder, and select the
  'Actions' menu, then 'Burn image'.

.Writing the image to a DVD in Mac OSX
. Download the .iso file
. Right-click on the file in the Finder window and select "Burn to disc"
  (The option to burn to disc  will only appear if the machine has an
  optical drive fitted or connected)

== Testing LinuxCNC

With the USB storage device plugged in or the DVD in the DVD drive,
shut down the computer then turn the computer back on. This will boot
the computer from the Live/Install Image and choose the Live boot option.

NOTE: If the system does not boot from the DVD or USB stick it might be
necessary to change the boot order in the PC BIOS.

Once the computer has booted up you can try out LinuxCNC without
installing it. You can not create custom configurations or modify most
system settings in a Live session, but you can (and should) run the
latency test.

To try out LinuxCNC: from the Applications/CNC menu pick LinuxCNC. A
dialog box will open from which you can choose one of many sample
configurations. At this point it only really makes sense to pick a "sim"
configuration. Some of the sample configurations include onscreen
3D simulated machines, look for "Vismach" to see these.

To see if your computer is suitable for software step pulse generation
run the Latency Test as shown <<sec:latency-test,here>>.

At the time of writing the Live-Image is only available with the
preempt-rt kernel and a matching LinuxCNC. On some hardware this might
not offer good enough latency. There is an experimental version available
using the RTAI realtime kernel which will often give better latency.

== Installing LinuxCNC

To install LinuxCNC from the LiveCD select 'Install (Graphical)' at
bootup.

== Updates to LinuxCNC(((Updates to LinuxCNC)))

With the normal install the Update Manager will notify you of updates
to LinuxCNC when you go on line and allow you to easily upgrade with no
Linux knowledge needed.
It is OK to upgrade everything except the operating system when asked to.

[WARNING]
Do not upgrade the operating system if prompted to do so. You
should accept OS _updates_ however, especially security updates.

[[linuxcnc:install-problems]]
== Install Problems(((LinuxCNC:Installation Problems)))(((Installation:Problems)))

In rare cases you might have to reset the BIOS to default settings if
during the Live CD install it cannot recognize the hard drive
during the boot up.

[[sec:_alternate_install_methods]]
== Alternate Install Methods(((LinuxCNC:Alternate Install Methods)))(((Installation:Alternate Methods)))

The easiest, preferred way to install LinuxCNC is to use the Live/Install
Image as described above.  That method is as simple and reliable as we
can make it, and is suitable for novice users and experienced users alike.
However, this will typically replace any existing operating system.

In addition, for experienced users who are familiar with Debian system
administration (finding install images, manipulating apt sources, changing
kernel flavors, etc), new installs are supported on following platforms:
("amd64" means "64-bit", and is not specific to AMD processors, it will
run on any 64-bit x86 system)

[options="header"]
|===
| Distribution    | Released | Architecture  | Kernel     | Package name    | Typical use
| Debian Bookworm | n/a      | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
| Debian Bookworm | n/a      | amd64 & armhf | preemp-rt  | linuxcnc-uspace | machine control & simulation
| Debian Bookworm | n/a      | amd64         | RTAI       | linuxcnc        | machine control (known issues)
| Debian Bullseye | 2021     | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
| Debian Bullseye | 2021     | amd64 & armhf | preemp-rt  | linuxcnc-uspace | machine control & simulation
| Debian Bullseye | 2021     | amd64         | RTAI       | linuxcnc        | machine control (known issues)
| Debian Buster*  | 2019     | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
| Debian Buster*  | 2019     | amd64 & armhf | preemp-rt  | linuxcnc-uspace | machine control & simulation
| Debian Buster*  | 2019     | amd64         | RTAI       | linuxcnc        | machine control (known issues)
| Debian Jessie*  | 2015     | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
| Debian Wheezy*   | 2013    | i386          | RTAI       | linuxcnc        | machine control & simulation
| Debian Wheezy*  | 2013     | amd64 & i386  | Preempt-RT | linuxcnc-uspace | machine control & simulation
| Debian Wheezy*  | 2013     | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
| Ubuntu Precise* | 2012     | i386          | RTAI       | linuxcnc        | machine control & simulation
| Ubuntu Precise* | 2012     | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
|===

Distributions marked with (*) are end of life and no longer receive security patches.

NOTE: LinuxCNC v2.8 is not supported on Ubuntu Lucid or older.

.Preempt-RT kernels
The Preempt-rt kernels are available for Debian from the regular debian.org archive.
The preempt-rt kernel for RaspBerry Pi is available from the LinuxCNC repository.
The package is called `linux-image-rt-*`.
Simply install the package in the same way as any other package from the Synaptic Package manager or with `apt-get` at the command-line.

.RTAI Kernels
The RTAI kernels are available for download from the linuxcnc.org debian archive.
The apt source is:

* Debian Buster: `deb https://linuxcnc.org buster base`
* Debian Wheezy: `deb https://linuxcnc.org wheezy base`
* Ubuntu Precise: `deb https://linuxcnc.org precise base`

[NOTE]
Both Debian Wheezy (released 2013, end of life 2016), Debian Buster (released 2019, end of life 2022) and Ubuntu Precise (released 2012, end of life 2017) are old, and are out of their support period.
It is strongly advised not to use either for a new install, and to seriously consider upgrading an existing installation.

The Buster / RTAI package is only available on amd64, but there are very few surviving systems that can not run a 64-bit OS.

[WARNING]
There are known issues with the 64-bit RTAI 5.2 kernel with this version of LinuxCNC.
The system will occasionally lock solid.
However, this has, so far, been seen only during system exit.
While running the system appears to be stable.
But should nevertheless be considered experimental at this point.

[NOTE]
If you decide to use the RTAI 5.2 kernel and see a problem outside the circumstances described above,
then please report it immediately to the project developers.

=== Installing on Debian Buster (with Preempt-RT kernel)

. Install Debian Buster (Debian 10), amd64 version. You can download the
  installer here: https://www.debian.org/releases/buster/ .

. After burning the iso and booting up, if you don't want Gnome desktop,
  select 'Advanced Options' > 'Alternative desktop environments' and pick the one you like.

. Then select 'Install' or 'Graphical Install'.

[WARNING]
Do not enter a root password, if you do sudo is disabled and you won't be able to complete the following steps.

. Run the following in a <<faq:terminal,terminal>> to bring the machine up to date with the latest packages.
+
----
sudo apt-get update
sudo apt-get dist-upgrade
----

. Install the Preempt-RT kernel and modules
+
----
sudo apt-get install linux-image-rt-amd64
----

. Re-boot, and select the Linux 4.19.0-9-rt-amd64 kernel (the exact kernel version might be different, look for the "-rt" suffix).
  This might be hidden in the "Advanced options for Debian Buster" sub-menu in Grub.
  When you log in, verify that `PREEMPT RT`is reported by the following command.
+
----
uname -v
----

. Open Applications Menu > System > Synaptic Package Manager,
  search for 'linux-image', right click on the original non-rt and select 'Mark for Complete Removal'.
  Reboot. This is to force the system to boot from the RT kernel.
  If you prefer to retain both kernels then the other kernels need not be deleted,
  but grub boot configuration changes will be needed beyond the scope of this document.

. Add the LinuxCNC Archive Signing Key to your apt keyring by running
+
----
sudo apt-key adv --keyserver hkp://keys.openpgp.org --recv-key 3cb9fd148f374fef
Alternate keyserver: keyserver.ubuntu.com
----

. Add the apt repository:
+
----
echo deb https://linuxcnc.org/ buster base 2.8-rtpreempt | sudo tee -a /etc/apt/sources.list.d/linuxcnc.list
echo deb-src https://linuxcnc.org/ buster base 2.8-rtpreempt | sudo tee -a /etc/apt/sources.list.d/linuxcnc.list
----

. Update the package list from linuxcnc.org
+
----
sudo apt-get update
----

. Install uspace (a reboot may be required prior to installing uspace)
+
----
sudo apt-get install linuxcnc-uspace
----

. Optionally you can install mesaflash if you are using a Mesa card.
+
----
sudo apt install mesaflash
----

[[cha:Installing-RTAI]]
=== Installing on Debian Buster (with experimental RTAI kernel)

[WARNING]
This kernel has known stability problems. It appears to run reliably once LinuxCNC is loaded.
However, kernel panics have been seen at system shut-down.

. This kernel and LinuxCNC version can be installed on top of the LiveDVD install,
  or alternatively on a fresh Install of Debian Buster 64-bit as described above.
. Add the LinuxCNC Archive Signing Key to your apt keyring
  (Not necessary if switching the realtime mode of a LinuxCNC Live-CD image).
+
----
# Alternate keyserver: keyserver.ubuntu.com
sudo apt-key adv --keyserver hkp://keys.openpgp.org --recv-key 3cb9fd148f374fef
----

. Add the apt repository:
+
----
echo deb https://linuxcnc.org/ buster base 2.8-rt | sudo tee /etc/apt/sources.list.d/linuxcnc.list
echo deb-src https://linuxcnc.org/ buster base 2.8-rt | sudo tee -a /etc/apt/sources.list.d/linuxcnc.list
----

. Update the package list from linuxcnc.org
+
----
sudo apt-get update
----

. Install the new realtime kernel, RTAI and the rtai version of linuxcnc
+
----
sudo apt-get install linux-image-4.19.195-rtai-amd64
----

. Install the RTAI application layer
+
----
sudo apt-get install rtai-modules-4.19.195
----

. Install LinuxCNC (may be necessary to reboot before installing)
+
----
sudo apt-get install linuxcnc
----

Reboot the machine, ensuring that the system boots from the new 4.19.195-rtai kernel.

=== Installing on Debian Bookworm

. Download the debian bookworm RC 2 netinst ISO.
https://cdimage.debian.org/cdimage/bookworm_di_rc2/amd64/iso-cd/debian-bookworm-DI-rc2-amd64-netinst.iso[https://cdimage.debian.org/cdimage/bookworm_di_rc2/amd64/iso-cd/debian-bookworm-DI-rc2-amd64-netinst.iso]
. Download Balena Etcher from
https://www.balena.io/etcher[https://www.balena.io/etcher]
. Burn your image to a USB stick using etcher
. Insert the USB stick into your PC and boot into it. You may need to
enter the BIOS and change the boot order
. *[red]#Do# [big red]#not# add a root password*
. Give your PC a name.
. Add a new user and allocate a password. I normally make both the user
name and password the same as the PC name
. When it asks to select the GUI, select XFCE and deselect
gnome and Debian. Only Select XFCE. +
_Take care here, if you don't select any options you will end up with a text based prompt only and as you won't have a root account becaise you followed these instructions carefully, you won't be able to fix it without re-installing._
. Complete the install and boot into debian! +
_If you end up at a text mode only console and do happen to have a root account, type *su* to enter root account and type: */usr/sbin/usermod -aG sudo your-user-name* to add your user to the sudo group and enable sudo. Then type *sudo tasksel* to install the GUI environment. Reboot to finish installing the graphical user interface._
. Open a terminal window and Type the following lines: 
+
`sudo apt update` +
`sudo apt upgrade` 
. Install linuxcnc. Type: 
+
`sudo apt install linuxcnc-uspace linuxcnc-uspace-dev` +
_NOTE that PREEMPT_RT real time kernel is installed as a dependency of linuxcnc-uspace so it's not required to install it separately._
. If you are using mesa hardware type: 
+
`sudo apt install mesaflash`
. Reboot into preempt-rt (the real-time kernel)
. type uname -a (to check PREEMPT-RT kernel is running)
. Linuxcnc should be in the menus or open a terminal and type: +
`linuxcnc` + 
and run an axis sim to check its working
. From the menu settings/Power manager set the power settings to suit
your needs. You can turn off screen saver and screen lock here
. Install geany and grub-customizer: +
`sudo apt install geany grub-customizer` +
. Finally now geany is installed, enable auto login +
`sudo geany /etc/lightdm/lightdm.conf` +
. Scroll down to about line 126 and uncomment (remove #) both
of the following lines and add YOUR login user name. Eg an example for user matt. +
`autologin-user=matt` + 
`autologin-user-timeout=0` +

==== Optional steps:

_Note that isolcpus can make a huge difference to latency on some systems because it isolates specific CPU cores so they are purely used by real time threads (eg the linuxcnc servo thread). The instructions below assume a 4 core CPU (eg. Celeron, i3, i5 etc) those with 2 cores or more than 4 cores need different isolcpus settings. Never isolate core 0 as it is used for system threads so it already includes a lot of running threads._
[start=20]
. Now we need to isolate 2 cores for better RT performance +
`sudo grub-customizer` +
. On the General Settings in the kernel parameters field, change it
from: +
`quiet` +
to: +
`quiet isolcpus=2,3` +
. Save the config, close grub-customiser and reboot for changes to take effect
. Check latency with: +
`latency-histogram --nobase --sbins=1000` + 
It should be much improved

==== Set fixed ip address - only for mesa card.

_Usually we set up the mesa card to have the ip address 10.10.10.10. We need to set a fixed ip address of 10.10.10.1 to the network interface that connects to it._
[start=24]
. To determine the network interface name used for
your mesa card, type: `ip a` This is usually something like *eth0* or *enp2s0*
. Edit the interfaces file to setup the ethernet card: +
`sudo geany /etc/network/interfaces` +` 
then add to the end of the file: +
`auto enp2s0` +
`iface enp2s0 inet static` +
`address 10.10.10.1` +
`hardware-irq-coalesce-rx-usecs 0` +
Note the last line is only required for Intel network cards. It seems to be ignored on non-applicable hardware.
. Save and close geany
. Reboot to restart the network
. Ping the mesa card to confirm it's all working `ping 10.10.10.10`

==== Review latency

[arabic, start=29]
. Use latency-histogram instead of latency-test to review latency: +
`latency-histogram --nobase --sbins 1000` + 
How to evaluate latency is covered in the linuxcnc documents
. Among other things, latency is affected by:
.. BIOS settings
.. Isolcpus and other boot time settings
.. Kernel version used

==== Review network latency (mesa cards)

If network latency is excessive, the mesa card may not have enough time to complete its work before the servo cycle ends. If this happens, you will receive an error finishing read error and the mesa card will be disabled. This appears to be more prevalent with Realtek network devices. You can review network latency by looking at some linuxcnc parameters while linuxcnc is running.

[arabic, start=31]
. In a new terminal console type `halcmd show param hm2*tmax*` This will list the maximum time spent for network reads and writes in timer ticks. You can also display these parameters using halshow now that you know the names.
. You can convert timer ticks to usec (1000 usec per servo thread cycle)
by dividing by the cpu frequency reported by `latency-histogram --nobase --sbins 1000`
. You can also use ping to get an idea of network latency without
linuxcnc running. To test ping times, you must run the test at
a real time priority, and run the test for a long time, something like: +
`sudo chrt 99 ping -i .001 -q 10.10.10.10``

. Following these tests, we determined one PC was spending up to 80% of a servo cycle reading and writing on the network leaving little time to get real work done.
. Improving network latency with some realtek cards is discussed under a later heading.

==== Installing a later kernel

_Since the release of Debian Bullseye (Linux kernel 5.10), Real time
performance has been disappointing. In particular, network
latency when communicating with a Mesa ethernet card has been
generating *Error Finishing Read* Errors. This means that the network
latency left insufficient time for the servo thread cycle to complete in time._

_This appears to have been more prevalent with Realtek Network
interfaces. Fortunately, [.GramE]#each iteration# of the Linux kernel
has improved results, particularly since the release of 6.x kernels.
Debian Bookworm (Debian 12) is using the 6.1 kernel which is not too
bad. In our testing, we found that latency improved by 265% if we used the 6.3 kernel. We have compiled this version of the kernel for your convenience. Updated to the final 6.3 kernel on 1 May 2023_

*Only try installing it if you have exhausted all options* by following the steps below:

[arabic, start=36]
. Download the 2 deb files (image, source) from +
+
https://drive.google.com/drive/folders/1NzQIHnf9M_cHzuZCqSldVFGschOOxaER?usp=sharing[https://drive.google.com/drive/folders/1NzQIHnf9M_cHzuZCqSldVFGschOOxaER?usp=sharing] +
+
_The link above is to my latest kernel versions following the
final release of 6.3 kernel and the matching preempt_rt patches._
+
. Navigate to the Downloads folder and open a new Terminal session
. Install the debs as follows (pressing tab auto completes these commands.) +
`dpkg -i linux-source` (tab) +
`dpkg -i linux-image`  (tab) +
. Reboot into the new kernel
. Check that `uname -v` shows the 6.3 kernel is installed
. If it isn’t, use grub-customizer mentioned earlier to change the
kernel boot order and reboot again

==== Realtek network drivers

Some users have been reporting significant error finishing read issues with some Realtek NIC's.

There are two additional device drivers available in Debian for realtek cards;

*r8125-dkms* for 2.5 Gb network cards - RTL8125, RTL8125B(S)(G)

and

*r8168-dkms* for the following network cards RTL8111B/RTL8111C,
RTL8111D/RTL8111E, RTL8111F/RTL8111G(S), RTL8111H(S), RTL8118(A)(S),
RTL8119i, RTL8111L, RTL8111K, RTL8168B, RTL8168E, RTL8168H, RTL8111DP, RTL8111EP, RTL8111FP, RTL8411/RTL8411B, RTL8101E, RTL8102E, RTL8103E, RTL8105E, RTL8106E, RTL8107E, RTL8401, RTL8402

Installing the r8168-dkms driver improved network latency by 400% on our R8111 network card. Similar results were reported on other affected hardware.

For more information about this issue, read this forum sticky post

https://forum.linuxcnc.org/9-installing-linuxcnc/47696-installing-linuxcnc-and-debian-bookworm-on-problematic-hardware-eg-realtek-nic[https://forum.linuxcnc.org/9-installing-linuxcnc/47696-installing-linuxcnc-and-debian-bookworm-on-problematic-hardware-eg-realtek-nic]

The r8168-dkms and r8125-dkms drivers are in the non-free packages which are not included by default.

[arabic, start=42]
. You can see your driver if you type the following to identify your NIC name: `ip a``
. Now display the NIC info eg: `ethtool enps02`
. If it seems you could benefit from this driver, continue
. Type `sudo geany /etc/apt/sources.list`
. Add a space followed by *non-free* to each of the 4 lines that end
with *firmware-non-free* as follows: +
`deb http://deb.debian.org/debian/ bookworm main non-free-firmware
non-free` +
`deb-src# http://deb.debian.org/debian/ bookworm main
non-free-firmware non-free` +
`deb# http://security.debian.org/debian-security
bookworm-security main non-free-firmware non-free` +
`deb-src# http://security.debian.org/debian-security
bookworm-security main non-free-firmware non-free` +
. Save and close geany
. Type: `sudo apt update`
. You need to install some utilities. Type: +
`sudo apt install build-essential dkms`
. If you have not installed a later kernel as described above install
linux-headers. Type: +
`sudo apt install linux-headers-$(uname -r)``
. You can now install the r8168 or R8125 driver. Depending on your
driver, type:
`sudo apt install r8168-dkms`+
Or: +
`sudo apt install r8125-dkms``
. Reboot
. Check you still have a network driver with `ip a``
. Check you can still ping the mesa card `ping 10.10.10.10``
. If you have to remove this driver, it needs to be purged completely or you will have no network. Eg. +
`sudo apt purge r8168-dkms`

==== Ethercat

_Ethercat is a fieldbus technology to control servo and stepper drives as well as other I/O boards etc. It interfaces with linuxcnc but adds an additional layer of complexity to your configuration._

[arabic, start=56]
. Install Ethercat if required by following these instructions +
https://forum.linuxcnc.org/ethercat/45336-ethercat-installation-from-repositories-how-to-step-by-step?start=0[https://forum.linuxcnc.org/ethercat/45336-ethercat-installation-from-repositories-how-to-step-by-step?start=0] +
_Note that it's important to use the correct version of Debian in
sources.list and when generating a key. (Currently debian-testing for
bookworm). Note for some reason building debs has been disabled by the ethercat guys._

==== Spindle Control via#Modbus (RS485)

_An alternative to controlling your spindle instead of a 0-10 volt
potentiometer is to use a RS485 interface that exists on most VFD's.
This requires a RS485 interface or usb dongle on your PC. There are
several linuxcnc modules for controlling various VFD's. I use vfdmod and a BD600 [.GramE]#vfd#._

[arabic, start=57]
. Install vfdmod to control spindle VFD with RS485 if required: +
https://forum.linuxcnc.org/24-hal-components/38733-vfdmod-an-easy-vfd-control-over-modbus-rtu[https://forum.linuxcnc.org/24-hal-components/38733-vfdmod-an-easy-vfd-control-over-modbus-rtu] +
Start by downloading and installing the debs with gdebi or dpkg -i then follow the wiki instructions
. Settings for BD600 are here later in that thread: +
https://forum.linuxcnc.org/24-hal-components/38733-vfdmod-an-easy-vfd-control-over-modbus-rtu?start=80#236664[https://forum.linuxcnc.org/24-hal-components/38733-vfdmod-an-easy-vfd-control-over-modbus-rtu?start=80#236664]

==== QTPYVCP and Probe Basic

[arabic, start=59]
. Proceed to install qtpyvcp and probe basic by using the deb here: +
https://drive.google.com/drive/folders/14tM4MHqLw26ebGVavKvTBb3ptx_IIcj5?usp=sharing[https://drive.google.com/drive/folders/14tM4MHqLw26ebGVavKvTBb3ptx_IIcj5?usp=sharing] +
Note that you must run probe-basic from the desktop icon.
. If you wish to modify Probe Basic, you need the developer install.
Follow these instructions +
https://github.com/Lcvette/qtpyvcp-bookworm-installer[https://github.com/Lcvette/qtpyvcp-bookworm-installer] +
Note that you must run probe-basic from the desktop icon.

Note these links are provided as a convenience as qtpyvcp is not part of linuxcnc. For a more integrated GUI with similar probing features you might like to look at qtdragon which is included in the linuxcnc distribution. Ref: +
https://linuxcnc.org/docs/2.9/html/gui/qtdragon.html[https://linuxcnc.org/docs/2.9/html/gui/qtdragon.html]


==== CPU Governors

Some people have seen improved latency when changing CPU latency. In our case, performance with and without governors made no difference on a 4 core i3 3.4Mhz PC. Follow this link for information on how to change CPU governors to performance:+
https://moisescardona.me/changing-the-cpu-governor-to-performance-in-linux/[https://moisescardona.me/changing-the-cpu-governor-to-performance-in-linux/]

==== Upgrading Linuxcnc 2.9 Bookworm from the secret buildbot

Go to http://buildbot2.highlab.com/[http://buildbot2.highlab.com/]

==== Upgrading Linuxcnc 2.9 on Bookworm from source

Until Linuxcnc V 2.9 is officially released, the version in Bookworm is just a snapshot loaded from time to time. Once Linuxcnc 2.9 becomes the official release, it should get pushed to Debian and won't often change.

To upgrade to the latest version, you need to build from source. I have a video of how to do this:
+https://youtu.be/Oe4Hfq3G2_A[https://youtu.be/Oe4Hfq3G2_A]+
Its not that difficult and its well documented here: +
https://linuxcnc.org/docs/2.9/html/code/building-linuxcnc.html[https://linuxcnc.org/docs/2.9/html/code/building-linuxcnc.html] +

Proceed as follows: +
`sudo# apt install git dpkg-dev build-essentials` +
`cd ~` +
`git# clone https://github.com/LinuxCNC/linuxcnc.git linuxcnc-dev` +
`cd ~/linuxcnc-dev` +
`git checkout 2.9` +

We now have the source so we need to make a deb file (1)+

`cd ~/linuxcnc-dev/debian` +
`./configure uspace no-docs` +

This will list all of the missing dependencies. Copy this list into a
text editor. Edit it to remove any brackets, version information etc
copy the list to your text editor type the following and past the list at the end of the line. On
`sudo# apt install -y <<your list>>` +
`cd ..` +

Once installed, repeat the configure command again and if all is well,
continue otherwise install the missing ones until [.GramE]#its# clean.
So when done, continue (this will take a while) +

`dpkg-buildpackage -b -uc` +

Occasionally, a missing dependency is reported when this is running,  install it with sudo apt install -y and repeat. At this point, your home folder should contain several .deb files. We can ignore linuxcnc-uspace-dev for now as it won't have any significant
changes very often.

We now need to uninstall your existing deb back in step 11 and reinstall the new ones

`sudo apt remove linuxcnc-uspace` +
`cd ~` +
`ls` +
`dpkg -i linuxcnc-uspace_` (tab) +

That's it you have upgraded

If you need to update linuxcnc again you can just

`cd ~/linuxcnc/src` +

`git pull` +

And repeat the process starting again at (##1) above.


=== Installing on Raspbian 10

. Download a stock Raspbian image to an SD card and install in the
  https://www.raspberrypi.org/documentation/installation/installing-images/README.md[usual way].
. Boot the Pi and open a terminal.
. Add the LinuxCNC Archive Signing Key to your apt keyring.
+
----
# Alternate keyserver: keyserver.ubuntu.com
sudo apt-key adv --keyserver hkp://keys.openpgp.org --recv-key 3cb9fd148f374fef
----

. Add the apt repository:
+
----
echo deb https://linuxcnc.org/ buster base 2.8-rtpreempt | sudo tee /etc/apt/sources.list.d/linuxcnc.list
----

. Update the package list from linuxcnc.org
+
----
sudo apt-get update
----

. install the realtime kernel
+
----
sudo apt-get install linux-image-4.19.71-rt24-v7l+
----

. Install linuxcnc (a reboot may be required prior to installing)
+
----
sudo apt-get install linuxcnc-uspace
----

=== Installing on Ubuntu Precise

. Install Ubuntu Precise 12.04 x86 (32-bit). Any flavor should work (regular Ubuntu, Xubuntu, Lubuntu, etc).
  64-bit (AMD64) is currently not supported. You can download the installer here:
  http://releases.ubuntu.com/precise/
  Note the warnings that this release is out of support.
  But it is a way to install LinuxCNC with a well-tested RTAI kernel.

. Run the following to bring the machine up to date with the latest packages in Ubuntu Precise.
+
----
sudo apt-get update
sudo apt-get dist-upgrade
----

. Add the LinuxCNC Archive Signing Key to your apt keyring by running
+
----
# Alternate keyserver: keyserver.ubuntu.com
sudo apt-key adv --keyserver hkp://keys.openpgp.org --recv-key 3cb9fd148f374fef
----

. Add a new apt source
+
----
sudo add-apt-repository "deb https://linuxcnc.org/ precise base 2.8-rt"
----

. Fetch the package list from linuxcnc.org.
+
----
sudo apt-get update
----

. Install the RTAI kernel and modules by running
+
----
sudo apt-get install linux-image-3.4-9-rtai-686-pae rtai-modules-3.4-9-rtai-686-pae
----

. If you want to be able to build LinuxCNC from source using the git repo, also run
+
----
sudo apt-get install linux-headers-3.4-9-rtai-686-pae
----

. Reboot, and make sure you boot into the rtai kernel. When you log in,
  verify that the kernel name is 3.4-9-rtai-686-pae.
+
----
uname -r
----

. Run
+
----
sudo apt-get install linuxcnc
----

// vim: set syntax=asciidoc:
